### ISSUE TITLE
Custom FOV

### ISSUE THREAD

**Issue by Keith94** [LennardF1989/NiohResolution#1]
Nioh's default FOV looks a bit narrow (60-70 degrees?) and there's no option to change it unfortunately. :(
I was wondering if you can add support for using a custom FOV value with your tool? Or if you know some way to change it manually. Thanks!

**Comment by LennardF1989** [comment]
Good question! When time allows I'll see if I can find some offsets and a way to patch it statically. I really want to stay clear from trainers, it's an endless battle of writing back values to memory.

**Comment by Keith94** [comment]
Sounds great man, I appreciate you looking into it. :)

**Comment by SkacikPL** [comment]
Would it be possible to do same with shadow resolution?
Their default resolution value seems rather lacking, even at the maximum setting, IIRC someone made a cheat engine override for it but it's outdated and i couldn't find new offset for the value.

**Comment by LennardF1989** [comment]
Ah, familiar name @SkacikPL ;) As said before I really want to be able to patch things statically, otherwise this becomes a trainer which is bound to break with the next update. So if you can find a place where the sizes are maintained (like the resolutions), I can override it accordingly in a forward compatible way.

**Comment by SkacikPL** [comment]
To be honest, in the long run it probably won't matter. I doubt Koei Tecmo will be pushing any more patches for this game since it doesn't have any bugs and all features have been added.
