### ISSUE TITLE
Nioh 21:9 3440 by 1440 Resolution not working after 1.24.8 patch on 1st of September 2022

### ISSUE THREAD

**Issue by Singhmaa** [LennardF1989/NiohResolution#23]
I repatched the .exe file:
1980 > 3440
1080 > 1440 
1.0
Yes (to backup)
and then select 1080 in game settings before starting it - this is not working.
Can you please check if I am doing something wrong or this patch needs to be updated?
![image](https://user-images.githubusercontent.com/114118568/191655541-9a95aa93-df0d-430c-9946-66caaee604cc.png)

**Comment by LennardF1989** [comment]
Sorry, I somehow didn't get a notification of this. I will look into it.

EDIT: You are not running the latest version of the patcher. Please download v1.5.0.

I can tell, since the latest version added this line of text: "NOTE! This patcher is compatible with Nioh v1.24.07 and (potentially) newer. If you have an older version of the game, please use an older version of this patcher!"
